Register model functions wrapper
Deeplite/deeplite-torch-zoo pull request #113
Opened 2022-01-21 20:01 UTC by shahrukh-dl

2022-01-24 23:52 UTC, ivan-lazarevich requested changes

2022-01-24 23:52 UTC, ivan-lazarevich commented on deeplite_torch_zoo/utils/registry.py
> +class Model_Registry:
Could you please inherit this from the base `Registry` class?  The only method that's different is `register`

Also you can remove the source link here, one is enough for this file.

2022-01-24 23:52 UTC, ivan-lazarevich commented on deeplite_torch_zoo/utils/registry.py
> +MODEL_WRAPPER_REGISTRY = Model_Registry('model_wrappers')
Please move the creation of the registry to a different file, e.g. to `deeplite_torch_zoo.wrappers.wrapper`

2022-01-24 23:52 UTC, ivan-lazarevich commented on deeplite_torch_zoo/wrappers/models/classification/cifar100/densenet.py
> +@MODEL_WRAPPER_REGISTRY.register('densenet121','cifar100','classification')
Please add spaces in between strings here for code style

2022-01-24 23:52 UTC, ivan-lazarevich commented on deeplite_torch_zoo/wrappers/models/classification/cifar100/googlenet.py
> +@MODEL_WRAPPER_REGISTRY.register('googlenet','cifar100','classification')
Same here and elsewhere, please add spaces for code style

2022-01-24 23:52 UTC, ivan-lazarevich commented on deeplite_torch_zoo/wrappers/wrapper.py
> +    print ( "_"*80)
Please fix code style here, e.g. `print("_" * 80)`

2022-01-24 23:52 UTC, ivan-lazarevich commented on deeplite_torch_zoo/wrappers/wrapper.py
> +    print ( "_"*80)
same here in all prints

2022-01-24 23:52 UTC, ivan-lazarevich commented on deeplite_torch_zoo/utils/registry.py
> +class Model_Registry:
Also please name it something like `TupleKeyRegistry` - we might want to reuse the same class for e.g. dataset wrappers in the future.

2022-01-27 04:44 UTC, ivan-lazarevich commented
@shahrukh-dl BTW you will probably resolve the pylint errors due to variable names by removing the wildcard imports in the `wrappers.wrapper` file and other places. These imports are not needed since we are using registries.

2022-01-27 04:46 UTC, ivan-lazarevich commented on deeplite_torch_zoo/wrappers/wrapper.py
>  from deeplite_torch_zoo.wrappers.models import *
you can remove this wildcard import, since you are already using a registry. this would help resolve pylint issues.

2022-01-27 04:55 UTC, ivan-lazarevich commented on deeplite_torch_zoo/wrappers/wrapper.py
>  from deeplite_torch_zoo.wrappers.models import *
also please remove the wildcard imports in other places like `wrappers.models.objectdetection`'s __init__.py - with registries we probably can replace it with just submodule imports:

`import deeplite_torch_zoo.wrappers.models.yolo5` itself would for instance execute the code that would add yolo5 wrappers to the model registry.

2022-01-27 12:12 UTC, shahrukh-dl commented on deeplite_torch_zoo/utils/registry.py
> +MODEL_WRAPPER_REGISTRY = Model_Registry('model_wrappers')
That will be a problem if create the registry in wrapper, because all the models file are called from the wrapper.py and these model file like vgg will be importing the wrapper, so it will create cyclic import issue.

2022-01-28 14:33 UTC, shahrukh-dl commented on deeplite_torch_zoo/wrappers/wrapper.py
> +    print ( "_"*80)
Fixed

2022-01-28 14:34 UTC, shahrukh-dl commented on deeplite_torch_zoo/wrappers/wrapper.py
> +    print ( "_"*80)
Fixed

2022-01-28 15:14 UTC, ivan-lazarevich commented on deeplite_torch_zoo/utils/registry.py
> +MODEL_WRAPPER_REGISTRY = Model_Registry('model_wrappers')
Got it. Let's keep it here for now then.

2022-01-28 15:22 UTC, ivan-lazarevich approved these changes

2022-01-28 15:24 UTC, merged