[draft] CamVid smp segmentation
Deeplite/deeplite-torch-zoo pull request #299
Opened 2023-05-02 01:04 UTC by lzrwch

2023-05-02 20:32 UTC, ahmed-deeplite requested changes

2023-05-02 20:32 UTC, ahmed-deeplite commented on training_scripts/segmentation/train_smp.py
> +from segmentation_models_pytorch import utils
where  does`segmentation_models_pytorch` come from?

2023-05-02 20:32 UTC, ahmed-deeplite commented on training_scripts/segmentation/train_smp.py
> +x_train_dir = os.path.join(DATA_DIR, 'train')
Please follow our conventions for creating dataloaders. Use `get_data_splits_by_name` https://github.com/Deeplite/deeplite-torch-zoo/blob/7c4d9d6dfb16e7e4d6ff43773b2c13de4874af18/deeplite_torch_zoo/wrappers/wrapper.py#L28

2023-05-02 20:32 UTC, ahmed-deeplite commented on training_scripts/segmentation/train_smp.py
> +class Dataset(BaseDataset):
Please, separate the Dataset files from the training loop

2023-05-02 20:32 UTC, ahmed-deeplite commented on training_scripts/segmentation/train_smp.py
> +model = smp.FPN(
Please create a separate file for the model

2023-05-03 16:16 UTC, lzrwch commented on training_scripts/segmentation/train_smp.py
> +from segmentation_models_pytorch import utils
@honnesh-deeplite add it to setup.py

2023-05-03 16:16 UTC, lzrwch commented on training_scripts/segmentation/train_smp.py
> +def get_training_augmentation():
also place augmentations to a separate file under src/

2023-05-19 00:23 UTC, lzrwch commented
@honnesh-deeplite please structure the PR in accordance to zoo structure:

in `deeplite_torch_zoo/src/semantic_segmentation`:
    - in `datasets` folder, place the CamVid and Cityscapes dataset objects in separate files

in `deeplite_torch_zoo/wrappers`:
    - in `datasets/semantic_segmentation` a file with a wrapper fn that creates dataloaders
    - in `eval/semantic_segmentation` a file with a wrapper fn for metrics taken from smp
    - in `eval/models` a file with a wrapper method to create Unet models with custom timm backbones

2023-08-14 20:55 UTC, closed without merging