added ffcv training support
Deeplite/deeplite-torch-zoo pull request #307
Opened 2023-06-06 08:15 UTC by ravishk007

Training is working

2023-06-06 19:32 UTC, lzrwch requested changes

2023-06-06 19:32 UTC, lzrwch commented on =1.21
> +Requirement already satisfied: numpy in /home/ravish/ffcv_venv/lib/python3.8/site-packages (1.19.5)
remove this file please

2023-06-06 19:32 UTC, lzrwch commented on training_scripts/classification/imagenet/time_new_calc.txt
> +/home/ravish/ffcv_exp/train_500_0.50_90.ffcv
remove this file please

2023-06-06 19:32 UTC, lzrwch commented on deeplite_torch_zoo/api/datasets/utils.py
> +def create_train_loader(train_dataset, num_workers, batch_size,
these are not generic utils, but rather methods to create data loaders specifically for imagenet, please move them to `deeplite_torch_zoo.api.datasets.classification.imagenet`

2023-06-06 19:32 UTC, lzrwch commented on deeplite_torch_zoo/api/datasets/utils.py
> +IMAGENET_MEAN = np.array([0.485, 0.456, 0.406]) * 255
these constants can be imported from here: https://github.com/Deeplite/deeplite-torch-zoo/blob/a3aa00ea427335df507df116d02fd4b2da34c83a/deeplite_torch_zoo/src/classification/augmentations/augs/augs.py#L11

2023-06-06 19:32 UTC, lzrwch commented on deeplite_torch_zoo/api/datasets/classification/imagenet.py
> +    train_loader = create_train_loader(train_dataset=os.path.join(data_root,train_split),
please rename this method to `create_ffcv_train_loader`

2023-06-06 19:32 UTC, lzrwch commented on deeplite_torch_zoo/api/datasets/classification/imagenet.py
> +    test_loader = create_val_loader(val_dataset=os.path.join(data_root,val_split),
please rename this method to `create_ffcv_train_loader`

2023-06-06 19:32 UTC, lzrwch commented on deeplite_torch_zoo/api/datasets/classification/imagenet.py
> -    train_dataset = datasets.ImageFolder(
please leave the `ImageFolder` dataset and PyTorch dataloader as the default option, instead of removing them. You can instead introduce an additional arg to `get_imagenet` e.g. `dataloading='pytorch'` (default), and return FFCV data loaders only in case `dataloading='ffcv'`

2023-06-07 07:31 UTC, ravishk007 commented on =1.21
> +Requirement already satisfied: numpy in /home/ravish/ffcv_venv/lib/python3.8/site-packages (1.19.5)
Done

2023-06-07 07:31 UTC, ravishk007 commented on training_scripts/classification/imagenet/time_new_calc.txt
> +/home/ravish/ffcv_exp/train_500_0.50_90.ffcv
Done

2023-06-07 07:31 UTC, ravishk007 commented on deeplite_torch_zoo/api/datasets/utils.py
> +def create_train_loader(train_dataset, num_workers, batch_size,
Done

2023-06-07 07:31 UTC, ravishk007 commented on deeplite_torch_zoo/api/datasets/utils.py
> +IMAGENET_MEAN = np.array([0.485, 0.456, 0.406]) * 255
Did this

2023-06-07 07:31 UTC, ravishk007 commented on deeplite_torch_zoo/api/datasets/classification/imagenet.py
> +    train_loader = create_train_loader(train_dataset=os.path.join(data_root,train_split),
Done

2023-06-07 07:32 UTC, ravishk007 commented on deeplite_torch_zoo/api/datasets/classification/imagenet.py
> +    test_loader = create_val_loader(val_dataset=os.path.join(data_root,val_split),
Done

2023-06-07 12:25 UTC, ravishk007 commented on deeplite_torch_zoo/api/datasets/classification/imagenet.py
> -    train_dataset = datasets.ImageFolder(
Done

2023-06-07 12:43 UTC, ravishk007 commented
@lzrwch pip3 install ffcv won't be successful until we install opencv from source. That's why these CIs are failing

2023-06-07 16:21 UTC, lzrwch requested changes

2023-06-07 16:21 UTC, lzrwch commented on deeplite_torch_zoo/api/datasets/classification/imagenet.py
> +        print("********",train_split)
please remove this line. if you wish to add someting to the log, please use 

```
from deeplite_torch_zoo.utils import LOGGER

LOGGER.info(...) 
```
or `debug`/`warning` instead of `info` as needed

2023-06-07 16:21 UTC, lzrwch commented on deeplite_torch_zoo/api/datasets/classification/imagenet.py
> +        print("********",train_split)
you can add a line informing that FFCV data loader will be used

2023-06-07 16:21 UTC, lzrwch commented on deeplite_torch_zoo/api/datasets/utils.py
> +from ffcv.pipeline.operation import Operation
since FFCV installation requires building other deps from source, let's assume that FFCV is not installed by default.

you add can a check like

```
try:
    import ffcv
    ... (all ffcv imports)
    FFCV_INSTALLED = True
except ImportError:
    FFCV_INSTALLED = False
```

2023-06-07 16:21 UTC, lzrwch commented on deeplite_torch_zoo/api/datasets/utils.py
> +        this_device = f'cuda:{0}'
here you can throw an error in case FFCV not installed

```
if not FFCV_INSTALLED:
    raise RuntimeError('FFCV installation is required')
```

2023-06-07 16:21 UTC, lzrwch commented on setup.py
> +    "ffcv",
remove this from setup.py since building 3rd party deps is required for installation. we can just provide a message that manual FFCV installation is required in case that feature is used (see above)

2023-06-07 16:21 UTC, lzrwch commented on deeplite_torch_zoo/api/datasets/utils.py
> +        this_device = f'cuda:{0}'
@ravishk007 you can also add a link to our installation instruction in the log message

2024-04-02 16:02 UTC, closed without merging