Adding Pascal raw dataset
Deeplite/deeplite-torch-zoo pull request #349
Opened 2023-08-24 14:01 UTC by hossein-dl

Adding pascal raw dataset. 
Depends on https://github.com/Deeplite/deeplite-torch-zoo/pull/342/files to finalize.

2023-08-24 17:05 UTC, lzrwch commented
@hossein-dl you can add rawpy to setup.py here as well

2023-08-24 17:14 UTC, lzrwch requested changes

2023-08-24 17:14 UTC, lzrwch commented on tests/test_raw_dataset_loading.py
> +DATASETS_ROOT = Path('/public-shared/datasets/RAW_DATASETS/custom_data/pascal_cropped_clf/raw')
we have no `/public-shared/` in CI. please create a small downloadable version of this dataset for testing, upload to our S3, and have it downloaded automatically in order to run tests in CI

2023-08-24 17:14 UTC, lzrwch commented on deeplite_torch_zoo/api/datasets/classification/pascalraw.py
> +class PASCALRAWDataset(Dataset):
please add the dataset class definition [here](https://github.com/Deeplite/deeplite-torch-zoo/tree/develop/deeplite_torch_zoo/src/classification/datasets). if the code was taken from a third-party source, place it in a separate subdirectory there with a corresponding LICENSE file

2023-08-24 17:14 UTC, lzrwch commented on deeplite_torch_zoo/api/datasets/classification/pascalraw.py
> +    train_dataset = PASCALRAWDataset(root=image_folder, split='train', transform=train_transforms)
transforms can only be passed by the user, no augmentation by default?

2023-08-24 17:14 UTC, lzrwch commented on deeplite_torch_zoo/api/datasets/classification/pascalraw.py
> +        input_size=[224, 224, 3],
pls pass it as an arg with default value instead of hardcoding

2023-08-25 15:25 UTC, lzrwch commented
@hossein-dl why is this added to classification, is it a version of the dataset converted to a multi-label classification problem?

2023-08-25 15:26 UTC, lzrwch requested changes

2023-08-25 15:26 UTC, lzrwch commented on deeplite_torch_zoo/api/datasets/classification/pascalraw.py
> +        return image, label
labels have to be read to from a file and converted to a corresponding format, I suppose

2023-08-25 21:11 UTC, hossein-dl commented
> @hossein-dl why is this added to classification, is it a version of the dataset converted to a multi-label classification problem?

Yes, @shahrukh-dl has created a classification dataset from the original PascalRaw dataset.

2023-08-25 21:56 UTC, lzrwch commented
> > @hossein-dl why is this added to classification, is it a version of the dataset converted to a multi-label classification problem?
> 
> Yes, @shahrukh-dl has created a classification dataset from the original PascalRaw dataset.

Then please change the name to something like `PASCALRAWMultiLabelCls`

2023-08-25 21:57 UTC, lzrwch commented on deeplite_torch_zoo/api/datasets/classification/pascalraw.py
> +        return image, label
keeping in mind that this is multi-label cls (e.g. each label would be a tuple of ints)

2023-08-28 16:54 UTC, alexh-deeplite commented
@hossein-dl @lzrwch  I'm working on the object detection version of this dataset based on the YoloDataset class, and will submit as a separate PR when it is tested. Just wanted to let you know

2023-08-29 20:15 UTC, lzrwch commented
@alexh-deeplite @hossein-dl closing as per today's discussion

2023-08-29 20:15 UTC, closed without merging