Add Report for RAM Profiler
Deeplite/deeplite-torch-zoo pull request #381
Opened 2024-01-02 16:33 UTC by matteog11

Implemented a new feature to generate comprehensive RAM usage reports for model layers, providing both summary and detailed insights.

2024-01-05 16:42 UTC, alexh-deeplite requested changes
Let's add a test with a dummy model so we can get coverage of the code

2024-01-05 16:42 UTC, alexh-deeplite commented on deeplite_torch_zoo/utils/profiler/utils/trace.py
> +def filter_torch_scope(node):
is this still necessary if we use `module.named_children()` to get the scope name? I'm not sure it is needed since you updated the torch scope function to be simpler than the previous version. The old version added unnecessary words to the scope

2024-01-09 11:45 UTC, matteog11 commented on deeplite_torch_zoo/utils/profiler/utils/trace.py
> +def filter_torch_scope(node):
@alexh-deeplite I conducted a few manual tests on both ResNet18 and MobileNet-V2 to evaluate the usefulness of the filter_torch_scope function. Here's the testing code and the outputs.

```python
print(
    node.scopeName(),
    node.scopeName().replace('Flatten/', '', 1).replace('Flatten', '', 1), 
    filter_torch_scope(node)
)
```

**ResNet18 Outputs:**
```
Flatten/ResNet[model]/Conv2d[conv1] ResNet[model]/Conv2d[conv1] conv1
Flatten/ResNet[model]/BatchNorm2d[bn1] ResNet[model]/BatchNorm2d[bn1] bn1
Flatten/ResNet[model]/Sequential[layer3]/BasicBlock[1]/ReLU[act2] ResNet[model]/Sequential[layer3]/BasicBlock[1]/ReLU[act2] layer3.1.act2
...
```

**MobileNet-V2 Outputs:**
```
Flatten/MobileNetV2[model]/Sequential[features]/Conv2dNormActivation[0]/Conv2d[0] MobileNetV2[model]/Sequential[features]/Conv2dNormActivation[0]/Conv2d[0] features.0.0
Flatten/MobileNetV2[model]/Sequential[features]/Conv2dNormActivation[0]/ReLU6[2] MobileNetV2[model]/Sequential[features]/Conv2dNormActivation[0]/ReLU6[2] features.0.2
Flatten/MobileNetV2[model]/Sequential[classifier]/Dropout[0] MobileNetV2[model]/Sequential[classifier]/Dropout[0] classifier.0
...
```

2024-01-09 17:54 UTC, alexh-deeplite commented on deeplite_torch_zoo/utils/profiler/utils/trace.py
> +def filter_torch_scope(node):
Looks good, I guess module types are still present

2024-01-28 05:41 UTC, merged