Ss/mcubench
Deeplite/deeplite-torch-zoo pull request #398
Opened 2024-07-30 03:10 UTC by sudhakar-sah

* Added MCUbench related files
* Updated [yolo.py](https://github.com/Deeplite/deeplite_torch_zoo/api/models/object_detection/yolo.py) to include MCUBench models and it can be accessed like other previous models 
* [mcubench](https://github.com/Deeplite/deeplite-torch-zoo/tree/ss/mcubench/results/mcubench) folder has all the files needed to recreate MCUBench. 
* Every mcubench file has instructions for usage.

2024-08-02 21:56 UTC, alexh-deeplite requested changes
one functional issue, the rest is all style

I will merge develop to this branch so we can see the build passing before merge

2024-08-02 21:56 UTC, alexh-deeplite commented on deeplite_torch_zoo/api/models/object_detection/yolo.py
> -    scale_dict = CUSTOM_MODEL_SCALES.get(_model_key, DEFAULT_MODEL_SCALES)
This line overwrites `CUSTOM_MODEL_SCALES` for the generation of non-mcu YOLO variants. We still want to use  `CUSTOM_MODEL_SCALES` when we call `get_model_scales` in line [239](https://github.com/Deeplite/deeplite-torch-zoo/blob/1b43d63c23d57b331f610bcd9589319a9f2f2670/deeplite_torch_zoo/api/models/object_detection/yolo.py#L239).

Simple fix is to pass the SCALES as an argument to `get_model_scales`

2024-08-02 21:56 UTC, alexh-deeplite commented on results/mcubench/benchmark_search_space_models.py
> +    python benchmark_search_space_models.py \
remove duplicate

2024-08-02 21:56 UTC, alexh-deeplite commented on results/mcubench/benchmark_search_space_models.py
> +with open("/public-shared/mcubench/models_list/search_space_models/search_space_models.json") as f:
remove hard coded path

2024-08-02 21:56 UTC, alexh-deeplite commented on results/mcubench/benchmark_search_space_models.py
> +        --data_path /public-shared/mcubench/mcubench_models/ \
remove path

2024-08-02 21:56 UTC, alexh-deeplite commented on results/mcubench/benchmark_search_space_models.py
> +    parser.add_argument('--data_path', type=str, default='/public-shared/mcubench/mcubench_models/', help='model and benchmark path')
remove default path

2024-08-02 21:56 UTC, alexh-deeplite commented on results/mcubench/benchmark_search_space_models.py
> +    # models_path = Path("/public-shared/mcubench/mcubench_models/448/checkpoints/voc/")
remove old code

2024-08-02 21:56 UTC, alexh-deeplite commented on results/mcubench/benchmark_first_pareto_models.py
> +# python benchmark_first_pareto_models.py --benchmarks_path /public-shared/mcubench/mcubench_models/pareto/estimated/ --models_path /public-shared/mcubench/mcubench_models/ --dataset voc --hw_name nu
remove

2024-08-02 21:56 UTC, alexh-deeplite commented on results/mcubench/benchmark_search_space_models.py
> +with open("/public-shared/mcubench/models_list/search_space_models/search_space_models.json") as f:
can just add a local symlink to the desired directory adn put the path to the symlink here

2024-08-02 21:56 UTC, alexh-deeplite commented on results/mcubench/one_for_all_mcubench_final.sh
replace hard coded paths with local symlinks or cli args

2024-08-13 22:07 UTC, sudhakar-sah commented on deeplite_torch_zoo/api/models/object_detection/yolo.py
> -    scale_dict = CUSTOM_MODEL_SCALES.get(_model_key, DEFAULT_MODEL_SCALES)
Fixed.

2024-08-13 22:08 UTC, sudhakar-sah commented on results/mcubench/benchmark_search_space_models.py
> +with open("/public-shared/mcubench/models_list/search_space_models/search_space_models.json") as f:
Added command line arguments.

2024-08-13 22:09 UTC, sudhakar-sah commented on results/mcubench/benchmark_search_space_models.py
> +    parser.add_argument('--data_path', type=str, default='/public-shared/mcubench/mcubench_models/', help='model and benchmark path')
removed.

2024-08-13 22:11 UTC, sudhakar-sah commented on results/mcubench/benchmark_first_pareto_models.py
> +# python benchmark_first_pareto_models.py --benchmarks_path /public-shared/mcubench/mcubench_models/pareto/estimated/ --models_path /public-shared/mcubench/mcubench_models/ --dataset voc --hw_name nu
Fixed.

2024-08-13 22:11 UTC, sudhakar-sah commented on results/mcubench/one_for_all_mcubench_final.sh
replaced.

2024-08-13 22:12 UTC, sudhakar-sah commented on results/mcubench/benchmark_search_space_models.py
> +    # models_path = Path("/public-shared/mcubench/mcubench_models/448/checkpoints/voc/")
fixed.

2024-08-13 22:13 UTC, sudhakar-sah commented on results/mcubench/benchmark_search_space_models.py
> +        --data_path /public-shared/mcubench/mcubench_models/ \
removed.

2024-08-13 22:14 UTC, sudhakar-sah reviewed
Updated the code based on review changes.

2024-08-14 19:01 UTC, merged